### ISSUE TITLE
midclt only accepts secrets on the command line

### ISSUE THREAD

**Issue by stephane-chazelas** [truenas/api_client#15]
On most systems, command line arguments are public information on the system and can be seen without restriction by any user/process (like in the output of `ps -Aww` on most Unix-like systems or `/proc/*/cmdline` on Linux-based systems). They also often end up in audit logs or shell history files.

Commands that can only accept secret information as arguments and do not provide safe alternatives are generally considered broken by design and cannot be used safely.

Please provide an alternative mechanism to pass secrets (password, API key) such as environment variables, config files or pass via file descriptors.

Some of the API calls can also involve supplying secret information, and command arguments usually have a limit on size, being able to pass the API request data over stdin or a file would also help.

**Comment by stephane-chazelas** [comment]
Thanks, but that only helps for interactive use and I'd expect `midclt` would mostly be used non-interactively. I was more thinking of something like:

```
diff --git a/truenas_api_client/__init__.py b/truenas_api_client/__init__.py
index 57ae351..260c770 100644
--- a/truenas_api_client/__init__.py
+++ b/truenas_api_client/__init__.py
@@ -900,6 +900,9 @@ def main():
                     elif args.api_key:
                         if not c.call('auth.login_with_api_key', args.api_key):
                             raise ValueError('Invalid API key')
+                    elif (key_from_env := os.getenv("TRUENAS_API_KEY")) is not None:
+                        if not c.call('auth.login_with_api_key', key_from_env):
+                            raise ValueError('Invalid API key')
                 except Exception as e:
                     print("Failed to login: ", e)
                     sys.exit(0)
```

**Comment by anodos325** [comment]
Generally we write targeted scripts using the python API client rather than doing automation with midclt commands. Latter is used at least by us only really in context of running one or two ad-hoc commands.
